on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: fredthedino/purerl:0.0.16
    steps:
      - uses: actions/checkout@v2
      - name: 'Compile'
        run: spago build
      - name: 'Test'
        run: spago test
